### PR TITLE
Added support to r/w image data as uint{16,32,64}

### PR DESCRIPTION
**Pull request by lenartj**
Some programs, for example Siril, saves image data with all pixels in
the 0-65535 with BZERO set 32768 and BITPIX is 16. So technically
you can read still read images into int16 by [pix X - #BZERO], but that
requires extra calculation and you end up with signed data, instead of
the original unsigned data. (You can't read most of these files without
this trick, i.e. 40000 would overflow int16.)

This patch adds support to read and write image data as uint16 (TUSHORT).
It enables reading such data files without extra calculations and preserves
the original data type.

### CODE REVIEW

**Comment by sbinet** [comment]
Thanks for the PR.
It would be great if a minimal test could be devised to exercise this new feature.

Also: wouldn't this be doable with the pure-Go sibling (a.k.a. [astrogo/fitsio](https://github.com/astrogo/fitsio)) of that library?

**Comment by lenartj** [comment]
:-)

I will add a few tests, sure. There is currently failing (unrelated) test
that should be fixed first (uint8 cards). I couldn't do that right away
hence no test yet.

I'm using the C fitsio library anyway so my binary is linked to fitsio
already so it makes sense for my use case to go with wrapper instead of
pure Go.

**Comment by lenartj** [comment]
Hi,

I have added some tests and fixed some unrelated test failures (see commit comments)

**Review by sbinet — APPROVED** [review]
LGTM.

could you send another PR against [astrogo/license](https://github.com/astrogo/license), adding yourself to the `AUTHORS` and/or `CONTRIBUTORS` files?

then I'll merge that one.

thanks again.

**Comment by lenartj** [comment]
Done, thanks for the really quick turnaround time

**Pull request merged**
